import type { Metadata } from "next";
import "./globals.css";
import * as styles from './page.tailwind';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={styles.layoutBodyContainer_tw}
      >
        {children}
      </body>
    </html>
  );
}
